[package]
name = "xsk-rs"
version = "0.5.0"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2018"
description = "Rust bindings for Linux AF_XDP sockets"
license = "MIT"
repository = "https://github.com/DouglasGray/xsk-rs"
readme = "README.md"
keywords = ["AF_XDP", "XSK", "eBPF", "XDP"]

[dependencies]
bitflags = "2.4.1"
cfg-if = "1.0.0"
libc = "0.2.135"
libxdp-sys = "0.2.0"
log = "0.4.17"

[dev-dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
ctrlc = "3.1"
env_logger = "0.9"
etherparse = "0.9"
futures = "0.3"
rand = "0.8"
rtnetlink = "0.7"
serial_test = "0.5"
structopt = "0.3"

[dev-dependencies.tokio]
version = "1.6"
default-features = false
features =  ["rt-multi-thread", "macros", "sync", "signal", "time"]
