[package]
name = "rust-xsk"
version = "0.1.0"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
libbpf-sys = "0.0.9-1"
bitflags = "1.2.1"
thiserror = "1.0.20"
log = "0.4"

[dev-dependencies]
rand = "0.7.3"
rtnetlink = "0.3.0"
futures = "0.3.5"
anyhow = "1.0.32"

[dev-dependencies.tokio]
version = "0.2.22"
default-features = false
features =  ["rt-core", "macros", "test-util", "time", "blocking"]
