[package]
name = "xsk-rs"
version = "0.2.2"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2018"
description = "Rust bindings for Linux AF_XDP sockets"
license = "MIT"
repository = "https://github.com/DouglasGray/xsk-rs"
readme = "README.md"
keywords = ["AF_XDP", "XSK", "eBPF", "XDP"]

[dependencies]
bitflags = "1.2"
libbpf-sys = "0.3.0-2"
libc = "0.2"
log = "0.4"

[dev-dependencies]
anyhow = "1.0"
clap = "2.33"
crossbeam-channel = "0.5"
ctrlc = "3.1"
etherparse = "0.9"
futures = "0.3"
rand = "0.8.3"
rtnetlink = "0.7"
env_logger = "0.8"

[dev-dependencies.tokio]
version = "1.6"
default-features = false
features =  ["rt-multi-thread", "macros", "sync", "signal"]
