[package]
name = "rust-xsk"
version = "0.1.0"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
libbpf-sys = "0.0.9-1"
bitflags = "1.2.1"
thiserror = "1.0.20"
log = "0.4"