[package]
name = "xsk-rs"
version = "0.1.0"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2018"
description = "Rust bindings for Linux AF_XDP sockets"
license = "MIT"
repository = "https://github.com/DouglasGray/xsk-rs"
readme = "README.md"
keywords = ["af_xdp", "xsk", "ebpf", "xdp"]

[dependencies]
bitflags = "1.2.1"
libbpf-sys = "0.0.9-1"
libc = "0.2"
log = "0.4"

[dev-dependencies]
anyhow = "1.0.32"
clap = "2.33.3"
criterion = "0.3.3"
etherparse = "0.9.0"
futures = "0.3.5"
rand = "0.7.3"
rtnetlink = "0.3.0"

[dev-dependencies.tokio]
version = "0.2.22"
default-features = false
features =  ["rt-core", "macros", "test-util", "blocking", "sync"]

[[bench]]
name = "link1_to_link2"
harness = false