name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt update
        sudo apt install libelf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: sudo ./run_all_tests.sh
